# Introduction to the Step 1 script----
# Script by D. Morreale 05/2023 
# This pipeline is adapted from Daniel Beiting's DIYtranscriptomics course, and has been heavily modified for analysis of human reads in this project.
# 05/11/2023 Living document that is being complied and modified. Incomplete pipeline.
# Pipeline relies on the psuedoaligned read counts generated by Kallisto and in the same directory as this R project
# "study_design.txt" is a tsv file with the subdirectories with "abundance.tsv" from kallisto
#   This file should have the smaple name as well as all metadata (bioreplicate, sampleID, treatment, hours post infection (HPI), library prep day (if applicable), which allows us to check for technical covariates)
# There are a few lines here that write out files, which include the paths on my device. Please alter as necessary
# Note: since there is no database for this, the read in chunk is highly modified. I generated a fake database using the gene annotations/gene id for KK01 in excel and saved as a tsv with the columns "target_id" (only locus tags used in Kallisto) and "gene_name" (annotaitons)

# Load Packages required for this script.----
# This includes all packages required to run this script
library(tidyverse) 
library(tximport) 
library(ensembldb) 
library(edgeR)
library(matrixStats)
library(cowplot)
library(DT)
library(plotly)
library(gt) 
library(limma)
library(beepr)
library(RColorBrewer)
library(gplots) 
library(heatmaply)


# Read in reports----
# Code in this code chunk written and distributed by D. Beiting in "Step1_TxImport.R"
targets <- read_tsv("study_design.txt")# read in your study design
path <- file.path(targets$sample, "abundance.tsv") # set file paths to your mapped data
trans_to_genes <- read_tsv("KK01_genenames.txt")
Tx <- as_tibble(trans_to_genes)

Txi_gene <- tximport(path, 
                     type = "kallisto", 
                     tx2gene = Tx, 
                     txOut = FALSE, # Since bacteiral transcript = genes, will change gene names later.
                     countsFromAbundance = "lengthScaledTPM",
                     ignoreTxVersion = TRUE)

# Manage your data----
# Code in this code chunk written and distributed by D. Beiting in "Step2_dataWrangling.R"
sampleLabels <- targets$Name
myDGEList <- DGEList(Txi_gene$counts)
log2.cpm <- cpm(myDGEList, log=TRUE)

log2.cpm.df <- as_tibble(log2.cpm, rownames = "geneID")
colnames(log2.cpm.df) <- c("geneID", sampleLabels)
log2.cpm.df.pivot <- pivot_longer(log2.cpm.df, # dataframe to be pivoted
                                  cols = Infected_1hpi_1:Uninfected_14hpi_4, # column names to be stored as a SINGLE variable
                                  names_to = "samples", # name of that new variable (column)
                                  values_to = "expression") # name of new variable (column) storing all the values (data)

p1 <- ggplot(log2.cpm.df.pivot) +
  aes(x=samples, y=expression, fill=samples) +
    geom_violin(trim = FALSE, show.legend = FALSE) +
    stat_summary(fun = "median", 
                 geom = "point", 
                 shape = 95, 
                 size = 10, 
                 color = "black", 
                 show.legend = FALSE) +
    labs(y="log2 expression", x = "sample",
         title="Log2 Counts per Million (CPM)",
         subtitle="unfiltered, non-normalized",
         caption=paste0("produced on ", Sys.time())) +
    theme_bw()

cpm <- cpm(myDGEList)
keepers <- rowSums(cpm>1)>=20 #USER DEFINED AND CAN BE CHANGED, this is selecting those w/ CPM > 1 for 5 or more of the samples
myDGEList.filtered <- myDGEList[keepers,]

log2.cpm.filtered <- cpm(myDGEList.filtered, log=TRUE)
log2.cpm.filtered.df <- as_tibble(log2.cpm.filtered, rownames = "geneID")
colnames(log2.cpm.filtered.df) <- c("geneID", sampleLabels)
log2.cpm.filtered.df.pivot <- pivot_longer(log2.cpm.filtered.df, # dataframe to be pivoted
                                           cols = Infected_1hpi_1:Uninfected_14hpi_4, # column names to be stored as a SINGLE variable
                                           names_to = "samples", # name of that new variable (column)
                                           values_to = "expression") # name of new variable (column) storing all the values (data)

p2 <- ggplot(log2.cpm.filtered.df.pivot) +
  aes(x=samples, y=expression, fill=samples) +
    geom_violin(trim = FALSE, show.legend = FALSE) +
    stat_summary(fun = "median", 
                 geom = "point", 
                 shape = 95, 
                 size = 10, 
                 color = "black", 
                 show.legend = FALSE) +
    labs(y="log2 expression", x = "sample",
         title="Log2 Counts per Million (CPM)",
         subtitle="filtered, non-normalized",
         caption=paste0("produced on ", Sys.time())) +
    theme_bw()

myDGEList.filtered.norm <- calcNormFactors(myDGEList.filtered, method = "TMM")
log2.cpm.filtered.norm <- cpm(myDGEList.filtered.norm, log=TRUE)
log2.cpm.filtered.norm.df <- as_tibble(log2.cpm.filtered.norm, rownames = "geneID")
colnames(log2.cpm.filtered.norm.df) <- c("geneID", sampleLabels)
log2.cpm.filtered.norm.df.pivot <- pivot_longer(log2.cpm.filtered.norm.df, 
                                                cols = Infected_1hpi_1:Uninfected_14hpi_4, 
                                                names_to = "samples", 
                                                values_to = "expression") 

p3 <- ggplot(log2.cpm.filtered.norm.df.pivot) +
  aes(x=samples, y=expression, fill=samples) +
    geom_violin(trim = FALSE, show.legend = FALSE) +
    stat_summary(fun = "median", 
                 geom = "point", 
                 shape = 95, 
                 size = 10, 
                 color = "black", 
                 show.legend = FALSE) +
    labs(y="log2 expression", x = "sample",
         title="Log2 Counts per Million (CPM)",
         subtitle="filtered, TMM normalized",
         caption=paste0("produced on ", Sys.time())) +
    theme_bw()

plot_grid(p1, p2, p3, labels = c('A', 'B', 'C'), label_size = 12)

# Variates----
# Code in this code chunk written and distributed by D. Beiting in "Step3_multivariate.R" but with significant modifications.

#These lines use edgeR to block the data by replicate and treatment (the two interesting variables)
Replicate <- factor(targets$replicate)
Treatment <- factor(targets$Treatment)
Time <- factor(targets$hpi)
design <- model.matrix(~Replicate+Treatment)

pca.res <- prcomp(t(log2.cpm.filtered.norm), scale.=F, retx=T)
pc.var <- pca.res$sdev^2 # sdev^2 captures these eigenvalues from the PCA result
pc.per <- round(pc.var/sum(pc.var)*100, 1) 
pca.res.df <- as_tibble(pca.res$x)

pca.plot.Replicate <- ggplot(pca.res.df) + #Check to see the data PCA distribution when groups are defined by Replicate (batch effect)
  aes(x=PC1, y=PC2, label=sampleLabels, color = Replicate) +
  geom_point(size=4) +
  stat_ellipse() +
  xlab(paste0("PC1 (",pc.per[1],"%",")")) + 
  ylab(paste0("PC2 (",pc.per[2],"%",")")) +
  labs(title="PCA plot") +
  coord_fixed() +
  theme_bw()

#ggplotly(pca.plot.Replicate) ##Uncomment if you want an interactive PCA plot

pca.plot.Treatment <- ggplot(pca.res.df) + #Check to see the data PCA distribution when groups are defined by treatment
  aes(x=PC1, y=PC2, label=sampleLabels, color = Treatment) +
  geom_point(size=4) +
  stat_ellipse() +
  xlab(paste0("PC1 (",pc.per[1],"%",")")) + 
  ylab(paste0("PC2 (",pc.per[2],"%",")")) +
  labs(title="PCA plot") +
  coord_fixed() +
  theme_bw()

# ggplotly(pca.plot.Treatment) ##Uncomment if you want an interactive PCA plot

# Replicate2 <- factor(targets$replicate)
# Time2 <- factor(targets$hpi)
# design2 <- model.matrix(~0+Time)
pca.plot.Time <- ggplot(pca.res.df) + #Check to see the data PCA distribution when groups are defined by treatment
  aes(x=PC1, y=PC2, label=sampleLabels, color = Time, linetype = Treatment) +
  geom_point(size=2) +
  stat_ellipse() +
  xlab(paste0("PC1 (",pc.per[1],"%",")")) + 
  ylab(paste0("PC2 (",pc.per[2],"%",")")) +
  labs(title="PCA plot") +
  coord_fixed() +
  theme_bw()
ggplotly(pca.plot.Time) ##Uncomment if you want an interactive PCA plot

plot_grid(pca.plot.Replicate, pca.plot.Treatment, pca.plot.Time, labels = c('A', 'B', "C"), label_size = 12, cols = TRUE)

mydata.df <- mutate(log2.cpm.filtered.norm.df,
#following block finds the averages of each condition across replicates
  uninfected_1hpi.AVG = (Uninfected_1hpi_1 + Uninfected_1hpi_2 + Uninfected_1hpi_3 + Uninfected_1hpi_4)/4, 
  uninfected_8hpi.AVG = (Uninfected_8hpi_1 + Uninfected_8hpi_2 + Uninfected_8hpi_3 + Uninfected_8hpi_4)/4,
  uninfected_14hpi.AVG = (Uninfected_14hpi_1 + Uninfected_14hpi_2 + Uninfected_14hpi_3 + Uninfected_14hpi_4)/4,
  infected_1hpi.AVG = (Infected_1hpi_1 + Infected_1hpi_2 + Infected_1hpi_3 + Infected_1hpi_4)/4, 
  infected_8hpi.AVG = (Infected_8hpi_1 + Infected_8hpi_2 + Infected_8hpi_3 + Infected_8hpi_4)/4,
  infected_14hpi.AVG = (Infected_14hpi_1 + Infected_14hpi_2 + Infected_14hpi_3 + Infected_14hpi_4)/4,
  #now make columns comparing each of the averages above that you're interested in
  LogFC_1hpi = (infected_1hpi.AVG - uninfected_1hpi.AVG),
  LogFC_8hpi = (infected_8hpi.AVG - uninfected_8hpi.AVG),
  LogFC_14hpi = (infected_14hpi.AVG - uninfected_14hpi.AVG)) %>% #note that this is the first time you've seen the 'pipe' operator
    mutate_if(is.numeric, round, 2)

# Create an CSV file (open with excel) of just the average log-fold change at each time point of interest, normalized by the uninfected control
datatable(mydata.df[,c(1,32:34)], 
  extensions = c('KeyTable', "FixedHeader"), 
  filter = 'top',
  options = list(keys = TRUE, 
                 searchHighlight = TRUE, 
                 pageLength = 10, 
                 dom = "Blfrtip", 
                 buttons = c("copy", "csv", "excel"),
                 lengthMenu = c("25", "50", "100")))

##Sort at each time point by fold change and make a table 
mydata.sort <- mydata.df %>%
  dplyr::arrange(desc(LogFC_14hpi)) %>% 
    dplyr::select(geneID, LogFC_1hpi, LogFC_8hpi, LogFC_14hpi)
write.csv(mydata.sort, "/Users/danielmorreale/RNA_seq/kallisto/Calu3_FC_sorted.csv", row.names=FALSE)


# Differentially Expressed Genes----
# Code in this code chunk written and distributed by D. Beiting in "Step5_diffGenes.R" but with heavy modifications.
# target2 <- read_tsv("study_design.txt") ## I Made a mistake, this should not actually be necessary if you set up your file right the first time :).
Replicate <- factor(targets$replicate)
Treatment <- factor(targets$Treatment)
Time <- factor(targets$hpi)
design <- model.matrix(~0+Time:Treatment)
colnames(design) <- gsub(":","_",colnames(design))
# Use limma to make a mean-variance model and plot the graph interactively. If you want it to run without plot, set "Plot = FALSE"
v.DEGList.filtered.norm <- voom(myDGEList.filtered.norm, design, plot = TRUE)
fit <- lmFit(v.DEGList.filtered.norm, design)

# Set up the pairwise comparisons you want to make
contrast.matrix <- makeContrasts(hpi_1 = Timehpi_1_TreatmentInfected - Timehpi_1_TreatmentUninfected,
                                 hpi_8 = Timehpi_8_TreatmentInfected - Timehpi_8_TreatmentUninfected,
                                 hpi_14 = Timehpi_14_TreatmentInfected - Timehpi_14_TreatmentUninfected,
                                 hpi_14rel1 = (Timehpi_14_TreatmentInfected - Timehpi_14_TreatmentUninfected) - (Timehpi_1_TreatmentInfected - Timehpi_1_TreatmentUninfected),
                                 hpi_8rel1 = (Timehpi_8_TreatmentInfected - Timehpi_8_TreatmentUninfected) - (Timehpi_1_TreatmentInfected - Timehpi_1_TreatmentUninfected),
                                 levels=design) # as many as you want...just add them above this line.


fits <- contrasts.fit(fit, contrast.matrix)
ebFit <- eBayes(fits) # get bayesian stats for your linear model fit
write.fit(ebFit, file="lmfit_results.txt")

# Notes:
# "adjust" is the correction model you are going to use to get your gene list, "BH" is Benjamini-Hocheberg
# "coef" is the comparison you are drawing, they exist in the same order that you put them in the make.contrasts
# "number" is the number of genes it'll spit out
# "sort.by" is just that
myTopHits_hpi_1 <- topTable(ebFit, adjust ="BH", coef=1, number=40000, sort.by="p") 
myTopHits_hpi_8 <- topTable(ebFit, adjust ="BH", coef=2, number=40000, sort.by="p") 
myTopHits_hpi_14 <- topTable(ebFit, adjust ="BH", coef=3, number=40000, sort.by="p") 
myTopHits_hpi_14rel1 <- topTable(ebFit, adjust ="BH", coef=4, number=40000, sort.by="p") 
myTopHits_hpi_8rel1 <- topTable(ebFit, adjust ="BH", coef=5, number=40000, sort.by="p") 

# Make a table of the boys
myTopHits_hpi_1.df <- myTopHits_hpi_1 %>% # This will need to be adjusted to match the above list.
  as_tibble(rownames = "geneID")
myTopHits_hpi_8.df <- myTopHits_hpi_8 %>% # This will need to be adjusted to match the above list.
  as_tibble(rownames = "geneID")
myTopHits_hpi_14.df <- myTopHits_hpi_14 %>% # This will need to be adjusted to match the above list.
  as_tibble(rownames = "geneID")
myTopHits_hpi_14rel1.df <- myTopHits_hpi_14rel1 %>% # This will need to be adjusted to match the above list.
  as_tibble(rownames = "geneID")
myTopHits_hpi_8rel1.df <- myTopHits_hpi_8rel1 %>% # This will need to be adjusted to match the above list.
  as_tibble(rownames = "geneID")


# Volcano plot it! Celebrate!! :)
vplot_1hpi <- ggplot(myTopHits_hpi_1.df) +
  aes(y=-log10(adj.P.Val), x=logFC, text = paste("Symbol:", geneID)) +
  geom_point(size=2) +
  geom_hline(yintercept = -log10(0.05), linetype=3, colour="grey", size=1) +
  geom_vline(xintercept = 1, linetype=3, colour="#BE684D", linewidth=1) +
  geom_vline(xintercept = -1, linetype=3, colour="#2C467A", linewidth=1) +
  labs(subtitle="Differentially Expressed genes at 1 h.p.i. infected relative to control", label_size=6) +
  theme_bw()

vplot_8hpi <- ggplot(myTopHits_hpi_8.df) +
  aes(y=-log10(adj.P.Val), x=logFC, text = paste("Symbol:", geneID)) +
  geom_point(size=2) +
  geom_hline(yintercept = -log10(0.05), linetype=3, colour="grey", size=1) +
  geom_vline(xintercept = 1, linetype=3, colour="#BE684D", linewidth=1) +
  geom_vline(xintercept = -1, linetype=3, colour="#2C467A", linewidth=1) +
  labs(subtitle="Differentially Expressed genes at 14 h.p.i. infected relative to control", label_size=6) +
  theme_bw()

vplot_14hpi <- ggplot(myTopHits_hpi_14.df) +
  aes(y=-log10(adj.P.Val), x=logFC, text = paste("Symbol:", geneID)) +
  geom_point(size=2) +
  geom_hline(yintercept = -log10(0.05), linetype=3, colour="grey", size=1) +
  geom_vline(xintercept = 1, linetype=3, colour="#BE684D", linewidth=1) +
  geom_vline(xintercept = -1, linetype=3, colour="#2C467A", linewidth=1) +
  labs(subtitle="Differentially Expressed genes at 14 h.p.i. infected relative to control", label_size=6) +
  theme_bw()
ggplotly(vplot_14hpi)

vplot_8hpirel1 <- ggplot(myTopHits_hpi_8rel1.df) +
  aes(y=-log10(adj.P.Val), x=logFC, text = paste("Symbol:", geneID)) +
  geom_point(size=2) +
  geom_hline(yintercept = -log10(0.05), linetype=3, colour="grey", size=1) +
  geom_vline(xintercept = 1, linetype=3, colour="#BE684D", linewidth=1) +
  geom_vline(xintercept = -1, linetype=3, colour="#2C467A", linewidth=1) +
  labs(subtitle="Differentially Expressed genes at 8 h.p.i. relative to 1 h.p.i", label_size=6) +
  theme_bw()

vplot_14hpirel1 <- ggplot(myTopHits_hpi_14rel1.df) +
  aes(y=-log10(adj.P.Val), x=logFC, text = paste("Symbol:", geneID)) +
  geom_point(size=2) +
  geom_hline(yintercept = -log10(0.05), linetype=3, colour="grey", size=1) +
  geom_vline(xintercept = 1, linetype=3, colour="#BE684D", linewidth=1) +
  geom_vline(xintercept = -1, linetype=3, colour="#2C467A", linewidth=1) +
  labs(subtitle="Volcano plot - Differentially Expressed genes at 14 h.p.i. relative to 1 h.p.i", label_size=6) +
  theme_bw()

# Make a figure
plot_grid(vplot_1hpi, vplot_8hpi, vplot_14hpi, vplot_8hpirel1, vplot_14hpirel1, labels = c('A', 'B', 'C', 'D', 'E'), label_size = 12)


results <- decideTests(ebFit, method="global", adjust.method="BH", p.value=0.05, lfc=1)
summary(results) ## See what you got

## Make a table of your comparisons
colnames(v.DEGList.filtered.norm$E) <- sampleLabels
diffGenes_1 <- v.DEGList.filtered.norm$E[results[,1] !=0,]
diffGenes_1.df <- as_tibble(diffGenes_1[,c("Infected_1hpi_1", "Infected_1hpi_2", "Infected_1hpi_3", "Infected_1hpi_4", "Uninfected_1hpi_1", "Uninfected_1hpi_2", "Uninfected_1hpi_3", "Uninfected_1hpi_4")], rownames = "geneID")
diffGenes_8 <- v.DEGList.filtered.norm$E[results[,2] !=0,]
diffGenes_8.df <- as_tibble(diffGenes_8[,c("Infected_8hpi_1", "Infected_8hpi_2", "Infected_8hpi_3", "Infected_8hpi_4", "Uninfected_8hpi_1", "Uninfected_8hpi_2", "Uninfected_8hpi_3", "Uninfected_8hpi_4")], rownames = "geneID")
diffGenes_14 <- v.DEGList.filtered.norm$E[results[,3] !=0,]
diffGenes_14.df <- as_tibble(diffGenes_14[,c("Infected_14hpi_1", "Infected_14hpi_2", "Infected_14hpi_3", "Infected_14hpi_4", "Uninfected_14hpi_1", "Uninfected_14hpi_2", "Uninfected_14hpi_3", "Uninfected_14hpi_4")], rownames = "geneID")
diffGenes_8rel1 <- v.DEGList.filtered.norm$E[results[,5] !=0,]
diffGenes_8rel1.df <- as_tibble(diffGenes_8rel1[,c("Infected_1hpi_1", "Infected_1hpi_2", "Infected_1hpi_3", "Infected_1hpi_4", "Uninfected_1hpi_1", "Uninfected_1hpi_2", "Uninfected_1hpi_3", "Uninfected_1hpi_4", "Infected_8hpi_1", "Infected_8hpi_2", "Infected_8hpi_3", "Infected_8hpi_4", "Uninfected_8hpi_1", "Uninfected_8hpi_2", "Uninfected_8hpi_3", "Uninfected_8hpi_4")], rownames = "geneID")
diffGenes_14rel1 <- v.DEGList.filtered.norm$E[results[,4] !=0,]
diffGenes_14rel1.df <- as_tibble(diffGenes_14rel1, rownames = "geneID")

# Makes some tables that are interactive in R studio
datatable(diffGenes_1.df,
          extensions = c('KeyTable', "FixedHeader"),
          caption = 'Table 1: DEGs in [CONDITION]',
          options = list(keys = TRUE, searchHighlight = TRUE, pageLength = 10, lengthMenu = c("10", "25", "50", "100"))) %>%
  formatRound(columns=c(2:11), digits=2)
datatable(diffGenes_8.df,
          extensions = c('KeyTable', "FixedHeader"),
          caption = 'Table 1: DEGs in [CONDITION]',
          options = list(keys = TRUE, searchHighlight = TRUE, pageLength = 25, lengthMenu = c("10", "25", "50", "100"))) %>%
  formatRound(columns=c(2:11), digits=2)
datatable(diffGenes_14.df,
          extensions = c('KeyTable', "FixedHeader"),
          caption = 'Table 1: DEGs in [CONDITION]',
          options = list(keys = TRUE, searchHighlight = TRUE, pageLength = 10, lengthMenu = c("10", "25", "50", "100"))) %>%
  formatRound(columns=c(2:11), digits=2)
# datatable(diffGenes_8rel1.df,
#           extensions = c('KeyTable', "FixedHeader"),
#           caption = 'Table 1: DEGs in [CONDITION]',
#           options = list(keys = TRUE, searchHighlight = TRUE, pageLength = 10, lengthMenu = c("10", "25", "50", "100"))) %>%
#   formatRound(columns=c(2:11), digits=2)
# datatable(diffGenes_14rel1.df,
#           extensions = c('KeyTable', "FixedHeader"),
#           caption = 'Table 1: DEGs in [CONDITION]',
#           options = list(keys = TRUE, searchHighlight = TRUE, pageLength = 10, lengthMenu = c("10", "25", "50", "100"))) %>%
#   formatRound(columns=c(2:11), digits=2)

write_tsv(diffGenes_1.df, "DE_genes_1hpi_infectvsuninfected.txt")
write_tsv(diffGenes_8.df, "DE_genes_8hpi_infectvsuninfected.txt")
write_tsv(diffGenes_14.df, "DE_genes_14hpi_infectvsuninfected.txt")
# write_tsv(diffGenes_8rel1.df, "DE_genes_8hpivs1hpi.txt")
# write_tsv(diffGenes_14rel1.df, "DE_genes_14hpivs1hpi.txt")

beepr::beep(sound=8)


# Make a heatmap ----

myheatcolors <- colorRampPalette(colors=c("blue","white","red"))(100)

diffGenes_1_subset <- diffGenes_1[,c("Infected_1hpi_1", "Infected_1hpi_2", "Infected_1hpi_3", "Infected_1hpi_4", "Uninfected_1hpi_1", "Uninfected_1hpi_2", "Uninfected_1hpi_3", "Uninfected_1hpi_4")]
diffGenes_8_subset <- diffGenes_8[,c("Infected_8hpi_1", "Infected_8hpi_2", "Infected_8hpi_3", "Infected_8hpi_4", "Uninfected_8hpi_1", "Uninfected_8hpi_2", "Uninfected_8hpi_3", "Uninfected_8hpi_4")]
diffGenes_14_subset <- diffGenes_14[,c("Infected_14hpi_1", "Infected_14hpi_2", "Infected_14hpi_3", "Infected_14hpi_4", "Uninfected_14hpi_1", "Uninfected_14hpi_2", "Uninfected_14hpi_3", "Uninfected_14hpi_4")]
diffGenes_8vs1_subset <- diffGenes_8rel1[,c("Infected_1hpi_1", "Infected_1hpi_2", "Infected_1hpi_3", "Infected_1hpi_4", "Uninfected_1hpi_1", "Uninfected_1hpi_2", "Uninfected_1hpi_3", "Uninfected_1hpi_4", "Infected_8hpi_1", "Infected_8hpi_2", "Infected_8hpi_3", "Infected_8hpi_4", "Uninfected_8hpi_1", "Uninfected_8hpi_2", "Uninfected_8hpi_3", "Uninfected_8hpi_4")]
diffGenes_allTP <- diffGenes_1[,c("Infected_1hpi_1", "Infected_1hpi_2", "Infected_1hpi_3", "Infected_1hpi_4", "Infected_8hpi_1", "Infected_8hpi_2", "Infected_8hpi_3", "Infected_8hpi_4", "Infected_14hpi_1", "Infected_14hpi_2", "Infected_14hpi_3", "Infected_14hpi_4", "Uninfected_1hpi_1", "Uninfected_1hpi_2", "Uninfected_1hpi_3", "Uninfected_1hpi_4", "Uninfected_8hpi_1", "Uninfected_8hpi_2", "Uninfected_8hpi_3", "Uninfected_8hpi_4", "Uninfected_14hpi_1", "Uninfected_14hpi_2", "Uninfected_14hpi_3", "Uninfected_14hpi_4")]

clustRows_1hpi <- hclust(as.dist(1-cor(t(diffGenes_1_subset), method="pearson")), method="complete")
clustRows_8hpi <- hclust(as.dist(1-cor(t(diffGenes_8_subset), method="pearson")), method="complete")
clustRows_14hpi <- hclust(as.dist(1-cor(t(diffGenes_14_subset), method="pearson")), method="complete")
clustRows_8vs1hpi <- hclust(as.dist(1-cor(t(diffGenes_8vs1_subset), method="pearson")), method="complete")
clustRows <- hclust(as.dist(1-cor(t(diffGenes_allTP), method="pearson")), method="complete")

clustColumns_1hpi <- hclust(as.dist(1-cor(diffGenes_1[,c("Infected_1hpi_1", "Infected_1hpi_2", "Infected_1hpi_3", "Infected_1hpi_4", "Uninfected_1hpi_1", "Uninfected_1hpi_2", "Uninfected_1hpi_3", "Uninfected_1hpi_4")], method="spearman")), method="complete")
clustColumns_8hpi <- hclust(as.dist(1-cor(diffGenes_8_subset, method="spearman")), method="complete")
clustColumns_14hpi <- hclust(as.dist(1-cor(diffGenes_14_subset, method="spearman")), method="complete")
clustColumns_8vs1hpi <- hclust(as.dist(1-cor(t(diffGenes_8vs1_subset), method="pearson")), method="complete")
clustColumns <- hclust(as.dist(1-cor(diffGenes_allTP, method="spearman")), method="complete")

module.assign_1hpi <- cutree(clustRows_1hpi, k=2)
module.assign_8hpi <- cutree(clustRows_8hpi, k=4)
module.assign_14hpi <- cutree(clustRows_14hpi, k=2)
module.assign_8vs1hpi <- cutree(clustRows_8vs1hpi, k=2)



heatmap_1hpi <- heatmap.2(diffGenes_1_subset,
          Rowv=as.dendrogram(clustRows_1hpi),
          Colv=as.dendrogram(clustColumns_1hpi),
          col=myheatcolors, scale='row', labRow=TRUE,
          density.info="none", trace="none",
          cexRow=1, cexCol=1, margins=c(8,15))
# 
# heatmap_8hpi <- heatmap.2(diffGenes_8_subset, 
#                           Rowv=as.dendrogram(clustRows_8hpi), 
#                           Colv=as.dendrogram(clustColumns_8hpi),
#                           #RowSideColors=module.color,
#                           col=rev(myheatcolors), scale='row', labRow=NA,
#                           density.info="none", trace="none",  
#                           cexRow=1, cexCol=1, margins=c(8,20))
# 
# heatmap_14hpi <- heatmap.2(diffGenes_14_subset, 
#                           Rowv=as.dendrogram(clustRows_14hpi), 
#                           Colv=as.dendrogram(clustColumns_14hpi),
#                           #RowSideColors=module.color,
#                           col=rev(myheatcolors), scale='row', labRow=NA,
#                           density.info="none", trace="none",  
#                           cexRow=1, cexCol=1, margins=c(8,20))
# 
# # heatmap_8vs1hpi <- heatmap.2(diffGenes_8vs1_subset, 
# #                           Rowv=as.dendrogram(clustRows_8vs1hpi), 
# #                           Colv=clustColumns_8vs1hpi,
# #                           col=rev(myheatcolors), scale='row', labRow=TRUE,
# #                           density.info="none", trace="none",  
# #                           cexRow=1, cexCol=1, margins=c(8,20))

# heatmap.2(diffGenes_allTP, 
#           Rowv=as.dendrogram(clustRows), 
#           Colv=clustColumns,
#           RowSideColors=module.color,
#           dendrogram = "row",
#           col=rev(myheatcolors), scale='row', labRow=NA,
#           density.info="none", trace="none",
#           keysize = 1,
#           cexRow=1, cexCol=1, margins=c(8,20))


# Better plot
module.assign <- cutree(clustRows, k=4)
module.color <- Purples(length(unique(module.assign)))
module.color <- module.color[as.vector(module.assign)]
heatmap.2(diffGenes_allTP, 
          Rowv=as.dendrogram(clustRows), 
          Colv=clustColumns,
          RowSideColors=module.color,
          colsep = c(0,4,8,12,16,20,24,28,32),
          rowsep = c(0,18,34,51,56),
          sepcolor = c("black"),
          sepwidth = c(0.05,0.05),
          dendrogram = "row",
          col=rev(myheatcolors), scale='row', labRow=NA,
          density.info="none", trace="none",
          keysize = 1,
          cexRow=1, cexCol=1, margins=c(8,20))
png("high_res_heatmap_bacteria.png", width = 8, height = 8, units = 'in', res = 600, bg = "transparent")

heatmap.2(diffGenes_allTP, 
          Rowv=as.dendrogram(clustRows), 
          Colv=clustColumns,
          RowSideColors=module.color,
          colsep = c(0,4,8,12,16,20,24,28,32),
          rowsep = c(0,18,34,51,56),
          sepcolor = c("black"),
          sepwidth = c(0.05,0.05),
          dendrogram = "row",
          col=rev(myheatcolors), scale='row', labRow=NA,
          density.info="none", trace="none",
          keysize = 1,
          cexRow=1, cexCol=1, margins=c(8,20))
dev.off()
